### ISSUE TITLE
Config-realted Crash?

### ISSUE THREAD

**Issue by Enderborn1235** [MtcLeo05/Soulmancy#33] opened 2024-11-18 19:06 UTC
[crash-2024-11-18_13.06.00-client.txt](https://github.com/user-attachments/files/17805148/crash-2024-11-18_13.06.00-client.txt)

**Comment by MtcLuna05** [comment] 2024-11-18 19:42
From what I can see the crash is caused by Lexicon, not Soulmancy

This line is what makes me think Lexicon is the problem:
`at TRANSFORMER/lexicon@1.8.2/xxrexraptorxx.lexicon.utils.Events.onClientTick(Events.java:46) ~[Lexicon-1.21-(v.1.8.2-NEO).jar%23440!/:1.21-(v.1.8.2-NEO)] {re:classloading}`

Have you tried reporting to the Lexicon mod author?

If the crash happens only when Soulmancy is added, lmk and also let the Lexicon mod author know

**Comment by Enderborn1235** [comment] 2024-11-19 15:04
[crash-2024-11-19_09.03.22-fml.txt](https://github.com/user-attachments/files/17817075/crash-2024-11-19_09.03.22-fml.txt)
It looks like its related to some terrablender code inside your mod

**Comment by Enderborn1235** [comment] 2024-11-19 15:05
Lexicon works fine. idk why it's part of the crash log.

**Comment by MtcLuna05** [comment] 2024-11-19 16:54
Which version of terrablender are you using? I tried with latest but no crash happened

**Comment by Enderborn1235** [comment] 2024-11-19 18:09
I am using version 4.1.0.5 for 1.21.1 Neoforge

**Comment by MtcLuna05** [comment] 2024-11-20 20:43
Then I'm sorry but I can't help you, since I can't reproduce no matter what I try.
I tried everything from a new instance to adding every single mod I could see from the log and it didn't crash.
I'll close the issue for now, if you're able to find a way to reproduce feel free to reopen

**Closed as completed** 2024-11-27 06:58 UTC
